import WalletContextProvider from '@/components/WalletContextProvider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Solana Wallet Connector Nextjs 14 Starter example',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    //wallet context provider
    <WalletContextProvider>
        <html lang="en">
            <body>{children}</body>
        </html>
    </WalletContextProvider>
  )
}
