name: Label Actions

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-actions:
    name: Label Actions
    runs-on: ubuntu-latest
    steps:
      - name: Label Actions
        uses: dessant/label-actions@v3
